### PR TITLE
Added Auth-login Test and Store Test 

### PR DESCRIPTION
**Pull request by Olanetsoft**

### CODE REVIEW

**Comment by Clish254** [comment]
Looks great! Bonus points, for every POST test add a DELETE test, i.e there should be a  /store/delete/:store_Id test and a /store/bank/delete/:acc_id test

**Comment by Olanetsoft** [comment]
Thank you @Clish254

**Comment by Clish254** [comment]
> Thank you @Clish254

/store/delete/:store_id test fails

**Comment by Olanetsoft** [comment]
> > Thank you @Clish254
> 
> /store/delete/:store_id test fails. `Cannot read property 'statusCode' of undefined`.Check your logic and make sure this doesn't happen.

works pretty fine. Maybe you should double-check. see screenshot below
image

**Review by Clish254 — APPROVED** [review]

**Comment by Clish254** [comment]
> > > Thank you @Clish254
> > 
> > 
> > /store/delete/:store_id test fails. `Cannot read property 'statusCode' of undefined`.Check your logic and make sure this doesn't happen.
> 
> @Clish254 it works pretty fine. Maybe you should double-check. see screenshot below
> image

This is what I get using the details from your initial config.env 
Screenshot from 2021-01-05 17-36-55

**Comment by Clish254** [comment]
Other than that, you successfully demonstrated your ability.

**Comment by Olanetsoft** [comment]
Thank you

**Pull request closed without merging**
